// Generated by view binder compiler. Do not edit!
package com.example.weatherapp.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.ProgressBar;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.weatherapp.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityFutureBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageView back;

  @NonNull
  public final ConstraintLayout background;

  @NonNull
  public final TextView citytxt;

  @NonNull
  public final TextView humidity;

  @NonNull
  public final ImageView imageView2;

  @NonNull
  public final ImageView imageView3;

  @NonNull
  public final ImageView imageView4;

  @NonNull
  public final TextView pressure;

  @NonNull
  public final ProgressBar progressBar;

  @NonNull
  public final RecyclerView recyclerView;

  @NonNull
  public final ScrollView scrollView;

  @NonNull
  public final TextView tempTxt;

  @NonNull
  public final TextView textView10;

  @NonNull
  public final TextView textView14;

  @NonNull
  public final TextView textView8;

  @NonNull
  public final ImageView weatherImg;

  @NonNull
  public final TextView weatherTxt;

  @NonNull
  public final TextView windSpeed;

  private ActivityFutureBinding(@NonNull ConstraintLayout rootView, @NonNull ImageView back,
      @NonNull ConstraintLayout background, @NonNull TextView citytxt, @NonNull TextView humidity,
      @NonNull ImageView imageView2, @NonNull ImageView imageView3, @NonNull ImageView imageView4,
      @NonNull TextView pressure, @NonNull ProgressBar progressBar,
      @NonNull RecyclerView recyclerView, @NonNull ScrollView scrollView, @NonNull TextView tempTxt,
      @NonNull TextView textView10, @NonNull TextView textView14, @NonNull TextView textView8,
      @NonNull ImageView weatherImg, @NonNull TextView weatherTxt, @NonNull TextView windSpeed) {
    this.rootView = rootView;
    this.back = back;
    this.background = background;
    this.citytxt = citytxt;
    this.humidity = humidity;
    this.imageView2 = imageView2;
    this.imageView3 = imageView3;
    this.imageView4 = imageView4;
    this.pressure = pressure;
    this.progressBar = progressBar;
    this.recyclerView = recyclerView;
    this.scrollView = scrollView;
    this.tempTxt = tempTxt;
    this.textView10 = textView10;
    this.textView14 = textView14;
    this.textView8 = textView8;
    this.weatherImg = weatherImg;
    this.weatherTxt = weatherTxt;
    this.windSpeed = windSpeed;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityFutureBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityFutureBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_future, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityFutureBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.back;
      ImageView back = ViewBindings.findChildViewById(rootView, id);
      if (back == null) {
        break missingId;
      }

      ConstraintLayout background = (ConstraintLayout) rootView;

      id = R.id.citytxt;
      TextView citytxt = ViewBindings.findChildViewById(rootView, id);
      if (citytxt == null) {
        break missingId;
      }

      id = R.id.humidity;
      TextView humidity = ViewBindings.findChildViewById(rootView, id);
      if (humidity == null) {
        break missingId;
      }

      id = R.id.imageView2;
      ImageView imageView2 = ViewBindings.findChildViewById(rootView, id);
      if (imageView2 == null) {
        break missingId;
      }

      id = R.id.imageView3;
      ImageView imageView3 = ViewBindings.findChildViewById(rootView, id);
      if (imageView3 == null) {
        break missingId;
      }

      id = R.id.imageView4;
      ImageView imageView4 = ViewBindings.findChildViewById(rootView, id);
      if (imageView4 == null) {
        break missingId;
      }

      id = R.id.pressure;
      TextView pressure = ViewBindings.findChildViewById(rootView, id);
      if (pressure == null) {
        break missingId;
      }

      id = R.id.progressBar;
      ProgressBar progressBar = ViewBindings.findChildViewById(rootView, id);
      if (progressBar == null) {
        break missingId;
      }

      id = R.id.recyclerView;
      RecyclerView recyclerView = ViewBindings.findChildViewById(rootView, id);
      if (recyclerView == null) {
        break missingId;
      }

      id = R.id.scrollView;
      ScrollView scrollView = ViewBindings.findChildViewById(rootView, id);
      if (scrollView == null) {
        break missingId;
      }

      id = R.id.tempTxt;
      TextView tempTxt = ViewBindings.findChildViewById(rootView, id);
      if (tempTxt == null) {
        break missingId;
      }

      id = R.id.textView10;
      TextView textView10 = ViewBindings.findChildViewById(rootView, id);
      if (textView10 == null) {
        break missingId;
      }

      id = R.id.textView14;
      TextView textView14 = ViewBindings.findChildViewById(rootView, id);
      if (textView14 == null) {
        break missingId;
      }

      id = R.id.textView8;
      TextView textView8 = ViewBindings.findChildViewById(rootView, id);
      if (textView8 == null) {
        break missingId;
      }

      id = R.id.weatherImg;
      ImageView weatherImg = ViewBindings.findChildViewById(rootView, id);
      if (weatherImg == null) {
        break missingId;
      }

      id = R.id.weatherTxt;
      TextView weatherTxt = ViewBindings.findChildViewById(rootView, id);
      if (weatherTxt == null) {
        break missingId;
      }

      id = R.id.windSpeed;
      TextView windSpeed = ViewBindings.findChildViewById(rootView, id);
      if (windSpeed == null) {
        break missingId;
      }

      return new ActivityFutureBinding((ConstraintLayout) rootView, back, background, citytxt,
          humidity, imageView2, imageView3, imageView4, pressure, progressBar, recyclerView,
          scrollView, tempTxt, textView10, textView14, textView8, weatherImg, weatherTxt,
          windSpeed);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
