// Generated by view binder compiler. Do not edit!
package com.example.weatherapp.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.ImageView;
import android.widget.ProgressBar;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.SearchView;
import androidx.cardview.widget.CardView;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.weatherapp.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityMainBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ConstraintLayout background;

  @NonNull
  public final CardView cardView;

  @NonNull
  public final TextView date;

  @NonNull
  public final TextView humidity;

  @NonNull
  public final ImageView imageView2;

  @NonNull
  public final ImageView imageView3;

  @NonNull
  public final ImageView imageView4;

  @NonNull
  public final ProgressBar loadingSpinner;

  @NonNull
  public final TextView minMaxTemp;

  @NonNull
  public final TextView next;

  @NonNull
  public final TextView pressure;

  @NonNull
  public final ProgressBar progressBar;

  @NonNull
  public final RecyclerView recyclerView;

  @NonNull
  public final ImageButton refreshBtn;

  @NonNull
  public final ScrollView scrollView2;

  @NonNull
  public final SearchView search;

  @NonNull
  public final TextView temp;

  @NonNull
  public final TextView textView10;

  @NonNull
  public final TextView textView12;

  @NonNull
  public final TextView textView8;

  @NonNull
  public final ImageView weatherimg;

  @NonNull
  public final TextView whether;

  @NonNull
  public final TextView windSpeed;

  private ActivityMainBinding(@NonNull ConstraintLayout rootView,
      @NonNull ConstraintLayout background, @NonNull CardView cardView, @NonNull TextView date,
      @NonNull TextView humidity, @NonNull ImageView imageView2, @NonNull ImageView imageView3,
      @NonNull ImageView imageView4, @NonNull ProgressBar loadingSpinner,
      @NonNull TextView minMaxTemp, @NonNull TextView next, @NonNull TextView pressure,
      @NonNull ProgressBar progressBar, @NonNull RecyclerView recyclerView,
      @NonNull ImageButton refreshBtn, @NonNull ScrollView scrollView2, @NonNull SearchView search,
      @NonNull TextView temp, @NonNull TextView textView10, @NonNull TextView textView12,
      @NonNull TextView textView8, @NonNull ImageView weatherimg, @NonNull TextView whether,
      @NonNull TextView windSpeed) {
    this.rootView = rootView;
    this.background = background;
    this.cardView = cardView;
    this.date = date;
    this.humidity = humidity;
    this.imageView2 = imageView2;
    this.imageView3 = imageView3;
    this.imageView4 = imageView4;
    this.loadingSpinner = loadingSpinner;
    this.minMaxTemp = minMaxTemp;
    this.next = next;
    this.pressure = pressure;
    this.progressBar = progressBar;
    this.recyclerView = recyclerView;
    this.refreshBtn = refreshBtn;
    this.scrollView2 = scrollView2;
    this.search = search;
    this.temp = temp;
    this.textView10 = textView10;
    this.textView12 = textView12;
    this.textView8 = textView8;
    this.weatherimg = weatherimg;
    this.whether = whether;
    this.windSpeed = windSpeed;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_main, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityMainBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      ConstraintLayout background = (ConstraintLayout) rootView;

      id = R.id.cardView;
      CardView cardView = ViewBindings.findChildViewById(rootView, id);
      if (cardView == null) {
        break missingId;
      }

      id = R.id.date;
      TextView date = ViewBindings.findChildViewById(rootView, id);
      if (date == null) {
        break missingId;
      }

      id = R.id.humidity;
      TextView humidity = ViewBindings.findChildViewById(rootView, id);
      if (humidity == null) {
        break missingId;
      }

      id = R.id.imageView2;
      ImageView imageView2 = ViewBindings.findChildViewById(rootView, id);
      if (imageView2 == null) {
        break missingId;
      }

      id = R.id.imageView3;
      ImageView imageView3 = ViewBindings.findChildViewById(rootView, id);
      if (imageView3 == null) {
        break missingId;
      }

      id = R.id.imageView4;
      ImageView imageView4 = ViewBindings.findChildViewById(rootView, id);
      if (imageView4 == null) {
        break missingId;
      }

      id = R.id.loading_spinner;
      ProgressBar loadingSpinner = ViewBindings.findChildViewById(rootView, id);
      if (loadingSpinner == null) {
        break missingId;
      }

      id = R.id.min_max_temp;
      TextView minMaxTemp = ViewBindings.findChildViewById(rootView, id);
      if (minMaxTemp == null) {
        break missingId;
      }

      id = R.id.next;
      TextView next = ViewBindings.findChildViewById(rootView, id);
      if (next == null) {
        break missingId;
      }

      id = R.id.pressure;
      TextView pressure = ViewBindings.findChildViewById(rootView, id);
      if (pressure == null) {
        break missingId;
      }

      id = R.id.progressBar;
      ProgressBar progressBar = ViewBindings.findChildViewById(rootView, id);
      if (progressBar == null) {
        break missingId;
      }

      id = R.id.recyclerView;
      RecyclerView recyclerView = ViewBindings.findChildViewById(rootView, id);
      if (recyclerView == null) {
        break missingId;
      }

      id = R.id.refreshBtn;
      ImageButton refreshBtn = ViewBindings.findChildViewById(rootView, id);
      if (refreshBtn == null) {
        break missingId;
      }

      id = R.id.scrollView2;
      ScrollView scrollView2 = ViewBindings.findChildViewById(rootView, id);
      if (scrollView2 == null) {
        break missingId;
      }

      id = R.id.search;
      SearchView search = ViewBindings.findChildViewById(rootView, id);
      if (search == null) {
        break missingId;
      }

      id = R.id.temp;
      TextView temp = ViewBindings.findChildViewById(rootView, id);
      if (temp == null) {
        break missingId;
      }

      id = R.id.textView10;
      TextView textView10 = ViewBindings.findChildViewById(rootView, id);
      if (textView10 == null) {
        break missingId;
      }

      id = R.id.textView12;
      TextView textView12 = ViewBindings.findChildViewById(rootView, id);
      if (textView12 == null) {
        break missingId;
      }

      id = R.id.textView8;
      TextView textView8 = ViewBindings.findChildViewById(rootView, id);
      if (textView8 == null) {
        break missingId;
      }

      id = R.id.weatherimg;
      ImageView weatherimg = ViewBindings.findChildViewById(rootView, id);
      if (weatherimg == null) {
        break missingId;
      }

      id = R.id.whether;
      TextView whether = ViewBindings.findChildViewById(rootView, id);
      if (whether == null) {
        break missingId;
      }

      id = R.id.windSpeed;
      TextView windSpeed = ViewBindings.findChildViewById(rootView, id);
      if (windSpeed == null) {
        break missingId;
      }

      return new ActivityMainBinding((ConstraintLayout) rootView, background, cardView, date,
          humidity, imageView2, imageView3, imageView4, loadingSpinner, minMaxTemp, next, pressure,
          progressBar, recyclerView, refreshBtn, scrollView2, search, temp, textView10, textView12,
          textView8, weatherimg, whether, windSpeed);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
