// Generated by view binder compiler. Do not edit!
package com.example.weatherapp.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.weatherapp.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ViewholderHourlyBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final TextView hourTxt;

  @NonNull
  public final ImageView pic;

  @NonNull
  public final TextView tempTxt;

  private ViewholderHourlyBinding(@NonNull LinearLayout rootView, @NonNull TextView hourTxt,
      @NonNull ImageView pic, @NonNull TextView tempTxt) {
    this.rootView = rootView;
    this.hourTxt = hourTxt;
    this.pic = pic;
    this.tempTxt = tempTxt;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ViewholderHourlyBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ViewholderHourlyBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.viewholder_hourly, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ViewholderHourlyBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.hourTxt;
      TextView hourTxt = ViewBindings.findChildViewById(rootView, id);
      if (hourTxt == null) {
        break missingId;
      }

      id = R.id.pic;
      ImageView pic = ViewBindings.findChildViewById(rootView, id);
      if (pic == null) {
        break missingId;
      }

      id = R.id.tempTxt;
      TextView tempTxt = ViewBindings.findChildViewById(rootView, id);
      if (tempTxt == null) {
        break missingId;
      }

      return new ViewholderHourlyBinding((LinearLayout) rootView, hourTxt, pic, tempTxt);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
